# Generated by Django 6.0.5 on 2026-06-05 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('website', models.URLField(blank=True)),
                ('careers_page', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=220)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('applied', 'Candidatura enviada'), ('confirmed', 'Recebida pela empresa'), ('screening', 'Triagem'), ('interview', 'Entrevista'), ('offer', 'Oferta'), ('rejected', 'Rejeitada'), ('withdrawn', 'Retirada'), ('archived', 'Arquivada')], default='draft', max_length=30)),
                ('source_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('remote', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.company')),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('manual_note', 'Nota manual'), ('email_update', 'Atualizacao por e-mail'), ('status_change', 'Mudanca de status'), ('reminder', 'Lembrete'), ('calendar_event', 'Evento de calendario')], max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'evento da candidatura',
                'verbose_name_plural': 'eventos da candidatura',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
