# Generated by Django 6.0.5 on 2026-06-07 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('website', models.URLField(blank=True)),
                ('careers_page', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Criado'), ('updated', 'Atualizado'), ('deleted', 'Excluido')], max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=120)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='applications.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de auditoria de empresa',
                'verbose_name_plural': 'logs de auditoria de empresa',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=220)),
                ('source_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('remote', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='applications.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_jobs', to=settings.AUTH_USER_MODEL)),
                ('directed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('applied', 'Candidatura enviada'), ('confirmed', 'Recebida pela empresa'), ('screening', 'Triagem'), ('interview', 'Entrevista'), ('offer', 'Oferta'), ('rejected', 'Rejeitada'), ('withdrawn', 'Retirada'), ('archived', 'Arquivada')], default='draft', max_length=30)),
                ('origin', models.CharField(choices=[('manual', 'Manual'), ('email', 'E-mail'), ('external', 'Externo')], default='manual', max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('next_action_type', models.CharField(blank=True, choices=[('follow_up', 'Follow-up'), ('interview', 'Entrevista'), ('send_document', 'Enviar documento'), ('await_response', 'Aguardar retorno'), ('other', 'Outro')], max_length=30)),
                ('next_action_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('manual_note', 'Nota manual'), ('email_update', 'Atualizacao por e-mail'), ('status_change', 'Mudanca de status'), ('reminder', 'Lembrete'), ('calendar_event', 'Evento de calendario')], max_length=30)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='applications.jobapplication')),
            ],
            options={
                'verbose_name': 'evento da candidatura',
                'verbose_name_plural': 'eventos da candidatura',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
