# Generated by Django 6.0.5 on 2026-06-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='data de anuncio'),
        ),
    ]
