# Generated by Django 6.0.5 on 2026-06-11 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_job_published_at'),
        ('email_ingestion', '0006_reabrir_legado_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='source_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_companies', to='email_ingestion.inboundemail'),
        ),
        migrations.AddField(
            model_name='job',
            name='source_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_jobs', to='email_ingestion.inboundemail'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='source_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_applications', to='email_ingestion.inboundemail'),
        ),
    ]
