# Generated by Django 6.0.5 on 2026-06-07 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutofillFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_domain', models.CharField(max_length=180)),
                ('field_label', models.CharField(max_length=180)),
                ('field_name', models.CharField(blank=True, max_length=180)),
                ('profile_source', models.CharField(help_text='Exemplo: candidate_profile.full_name ou saved_answer.cover_letter.', max_length=180)),
                ('fallback_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mapeamento de campo',
                'verbose_name_plural': 'mapeamentos de campo',
                'ordering': ['site_domain', 'field_label'],
                'unique_together': {('site_domain', 'field_label', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='AutofillSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_domain', models.CharField(max_length=180)),
                ('field_label', models.CharField(max_length=180)),
                ('field_name', models.CharField(blank=True, max_length=180)),
                ('suggested_value', models.TextField()),
                ('status', models.CharField(choices=[('suggested', 'Sugerido'), ('accepted', 'Aceito'), ('rejected', 'Rejeitado')], default='suggested', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autofill_suggestions', to='applications.jobapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autofill_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sugestao de preenchimento',
                'verbose_name_plural': 'sugestoes de preenchimento',
                'ordering': ['-created_at'],
            },
        ),
    ]
