"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def load_local_env(env_path: Path) -> None:
    """Carrega pares KEY=VALUE de .env local sem sobrescrever o ambiente real."""
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key:
            os.environ.setdefault(key, value)


# DJANGO_SKIP_DOTENV=1 ignora o .env local (usado em testes/CI para validar a
# configuracao de producao com um ambiente totalmente controlado).
if not os.environ.get('DJANGO_SKIP_DOTENV'):
    load_local_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'true').lower() == 'true'

# SECURITY WARNING: keep the secret key used in production secret!
# Em producao a chave e obrigatoria; o fallback inseguro vale apenas em DEBUG.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-development-key-change-before-production'
    else:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY e obrigatoria em producao.'
        )

if DEBUG:
    # Permite callback OAuth em http://localhost durante desenvolvimento local.
    os.environ.setdefault('OAUTHLIB_INSECURE_TRANSPORT', '1')

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Chave de criptografia dos tokens OAuth em repouso (Fernet, urlsafe-base64 de
# 32 bytes). Gere uma com:
#   python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Em producao e obrigatoria; em DEBUG ha um fallback inseguro so para dev/testes.
FIELD_ENCRYPTION_KEY = os.environ.get('DJANGO_FIELD_ENCRYPTION_KEY', '')
if not FIELD_ENCRYPTION_KEY:
    if DEBUG:
        FIELD_ENCRYPTION_KEY = 'ZGV2LWluc2VjdXJlLWtleS1jaGFuZ2UtaW4tcHJvZCE='
    else:
        raise ImproperlyConfigured(
            'DJANGO_FIELD_ENCRYPTION_KEY e obrigatoria em producao para '
            'criptografar os tokens OAuth.'
        )


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Autenticacao (django-allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # Apps do projeto
    'accounts',
    'applications',
    'email_ingestion',
    'candidate_profile',
    'notifications',
    'autofill',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Necessario para o django-allauth
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# O caminho do banco vem do ambiente. Em producao (e tambem em dev), aponte
# DJANGO_DB_PATH para fora de pastas sincronizadas (OneDrive/Dropbox/etc.) — o
# banco guarda tokens e corpos de e-mail e nao deve ser replicado para a nuvem.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.environ.get('DJANGO_DB_PATH', BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Autenticacao
# https://docs.allauth.org/

AUTH_USER_MODEL = 'accounts.User'

SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    # Backend padrao do Django (necessario para o Admin)
    'django.contrib.auth.backends.ModelBackend',
    # Backend do allauth (login por e-mail, social login)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Cadastro e login por e-mail (sem campo username visivel ao usuario).
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# Deploy local em rede domestica: nao exige verificacao de e-mail.
ACCOUNT_EMAIL_VERIFICATION = 'none'

LOGIN_REDIRECT_URL = 'home'
LOGIN_URL = 'account_login'
ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

# Credenciais OAuth do Google (login allauth + conexao Gmail da Etapa 3).
# Vem do ambiente; enquanto vazias, o login social e a conexao Gmail ficam
# inativos (a UI degrada com mensagem amigavel).
GOOGLE_OAUTH_CLIENT_ID = os.environ.get('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.environ.get('GOOGLE_OAUTH_CLIENT_SECRET', '')

# Escopos usados especificamente para conectar o Gmail (leitura). Restrito pelo
# Google — exige verificacao OAuth para uso publico (ver .specs/11).
GMAIL_OAUTH_SCOPES = [
    'openid',
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'https://www.googleapis.com/auth/gmail.readonly',
]
# Precisa bater exatamente com o redirect cadastrado no Google Cloud.
GMAIL_REDIRECT_URI = os.environ.get(
    'GMAIL_REDIRECT_URI', 'http://localhost:8000/email/gmail/callback/'
)

# O mesmo fluxo OAuth do Google autentica o usuario e, futuramente, autoriza
# o acesso ao Gmail (Etapa 3). As credenciais vem do ambiente — o provider so
# fica utilizavel apos GOOGLE_OAUTH_CLIENT_ID/SECRET serem definidos.
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APPS': [
            {
                'client_id': GOOGLE_OAUTH_CLIENT_ID,
                'secret': GOOGLE_OAUTH_CLIENT_SECRET,
                'key': '',
            },
        ],
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'offline'},
    },
}


# Endurecimento de producao. Ativado somente fora de DEBUG para nao atrapalhar o
# desenvolvimento local (HTTP em localhost). Exige deploy atras de HTTPS.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    # Deploy tipico atras de proxy reverso (nginx/Caddy) que termina o TLS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
