# Generated by Django 6.0.5 on 2026-06-08 18:02

import django.db.models.deletion
import email_ingestion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Microsoft 365'), ('imap', 'IMAP generico')], default='gmail', max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
                ('access_token', models.TextField(blank=True)),
                ('refresh_token', models.TextField(blank=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('scan_times', models.JSONField(default=email_ingestion.models.default_scan_times)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conta de e-mail',
                'verbose_name_plural': 'contas de e-mail',
                'ordering': ['email_address'],
            },
        ),
        migrations.CreateModel(
            name='EmailSenderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_domain', models.CharField(blank=True, max_length=180)),
                ('subject_keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_rules', to='applications.company')),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='email_ingestion.emailaccount')),
            ],
            options={
                'verbose_name': 'regra de remetente',
                'verbose_name_plural': 'regras de remetente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('sender', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField()),
                ('body_text', models.TextField(blank=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pendente'), ('classified', 'Classificado'), ('needs_review', 'Precisa revisao'), ('ignored', 'Ignorado')], default='pending', max_length=30)),
                ('inferred_application_status', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='applications.jobapplication')),
                ('email_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='email_ingestion.emailaccount')),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='email_ingestion.emailsenderrule')),
            ],
            options={
                'verbose_name': 'e-mail recebido',
                'verbose_name_plural': 'e-mails recebidos',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.TextField(blank=True)),
                ('suggested_status', models.CharField(blank=True, max_length=30)),
                ('rationale', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='email_ingestion.inboundemail')),
            ],
            options={
                'verbose_name': 'classificacao de e-mail',
                'verbose_name_plural': 'classificacoes de e-mail',
            },
        ),
        migrations.AddConstraint(
            model_name='emailaccount',
            constraint=models.UniqueConstraint(fields=('user', 'email_address'), name='unique_user_email_account'),
        ),
    ]
