# Generated by Django 6.0.5 on 2026-06-10 17:56

import email_ingestion.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaccount',
            name='access_token',
            field=email_ingestion.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='refresh_token',
            field=email_ingestion.fields.EncryptedTextField(blank=True),
        ),
    ]
