# Generated by Django 6.0.5 on 2026-06-10 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0002_emailclassification_reviewed_by'),
        ('email_ingestion', '0003_apagar_tokens_legados'),
    ]

    operations = [
    ]
