# Generated by Django 6.0.5 on 2026-06-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_ingestion', '0004_merge_20260610_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailclassification',
            name='is_new_opportunity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailclassification',
            name='suggested_company_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='emailclassification',
            name='suggested_role_title',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='emailclassification',
            name='suggested_source_url',
            field=models.URLField(blank=True),
        ),
    ]
